/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Registration;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Patient.Patient;
import Business.Role.PatientRole;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author cheta
 */
public class PatientRegistration extends javax.swing.JPanel {

    /**
     * Creates new form PatientRegistration
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public PatientRegistration(EcoSystem system) {
        initComponents();
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        userNamejTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        registerjButton = new javax.swing.JButton();
        resetjButton = new javax.swing.JButton();
        ageJTF = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(84, 162, 168));
        jLabel1.setText("Patient Registration");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(84, 162, 168));
        jLabel2.setText("Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, 10));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(84, 162, 168));
        jLabel3.setText("Age :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, 10));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(84, 162, 168));
        jLabel5.setText("Username :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(84, 162, 168));
        jLabel6.setText("Password :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, 10));
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 120, 30));
        add(userNamejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 120, 30));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 120, 30));

        registerjButton.setBackground(new java.awt.Color(255, 255, 255));
        registerjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registerjButton.setForeground(new java.awt.Color(84, 162, 168));
        registerjButton.setText("Register");
        registerjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerjButtonActionPerformed(evt);
            }
        });
        add(registerjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 80, 30));

        resetjButton.setBackground(new java.awt.Color(255, 255, 255));
        resetjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        resetjButton.setForeground(new java.awt.Color(84, 162, 168));
        resetjButton.setText("Reset");
        resetjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(resetjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 78, 30));
        add(ageJTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void registerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerjButtonActionPerformed
        // TODO add your handling code here:
        String name = namejTextField.getText();
        try{
            int age = Integer.parseInt(ageJTF.getText()); 
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory. Age should be a number greater than 0");
            return;
        }
       int age = Integer.parseInt(ageJTF.getText());
        //int ssn = Integer.parseInt(sSNjTextField1.getText());
        String username = userNamejTextField2.getText();
        String password = jPasswordField1.getText();
        
        if(!(name.equals("") || username.equals("") || password.equals("") || age<1)) {
            Patient patient = system.getPatientList().createPatient(name, age);
        UserAccount ua = system.getUserAccountDirectory().createPatientAccount(username, password, patient, new PatientRole());
        System.out.println(system.getPatientList().getPatientList().get(0));
            JOptionPane.showMessageDialog(null, "Registered successfully");
        dB4OUtil.storeSystem(system);
        }
        else {
            JOptionPane.showMessageDialog(null, "All fields are mandatory. Age should be a number greater than 0");
            return;
        }
        
        
    }//GEN-LAST:event_registerjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageJTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JButton registerjButton;
    private javax.swing.JButton resetjButton;
    private javax.swing.JTextField userNamejTextField2;
    // End of variables declaration//GEN-END:variables
}
