/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import javax.swing.JOptionPane;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author cheta
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    private Person person;
    public CreateJPanel(Person person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstNameTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lastNameFieldTxtfield = new javax.swing.JTextField();
        DOBTxtField = new javax.swing.JTextField();
        phoneNoTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        licNoTxtField = new javax.swing.JTextField();
        LicValidToTxtField = new javax.swing.JTextField();
        LicValidFromTxtField = new javax.swing.JTextField();
        ClassTxtField = new javax.swing.JTextField();
        IssuingCityTxtField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CreditCardNoTxtField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CCValidFromTxtField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        CCValidToTxtField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cCProviderTxtField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        middleNameTxtField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        streetNameTxtField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        apartmentNoTxtField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cityTxtField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        stateTxtField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        zipTxtField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        checkingAccNoTxtField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        checkCreatedOnTxtField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        checkingCreditTxtField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        checkDebitTxtField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        savingAccNoTxtField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        savingCreatedOnTxtField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        savingCreditTxtField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        savingDebitTxtField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cCActiveTxtField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        checkActiveTxtField = new javax.swing.JTextField();
        savingActiveTxtField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        createPanelButton = new javax.swing.JButton();
        Imagelabel = new javax.swing.JLabel();
        pathTxtField = new javax.swing.JTextField();
        AttachButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Create User Profile Information");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel3.setText("Credit Card Details");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setText("First Name:");

        firstNameTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        firstNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setText("Last Name :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel7.setText("Phone No :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel8.setText("D.O.B :");

        lastNameFieldTxtfield.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lastNameFieldTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldTxtfieldActionPerformed(evt);
            }
        });

        phoneNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoTxtFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel9.setText("Personal Details");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel10.setText("Valid From :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel11.setText("Licence No :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel12.setText("Valid To:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel13.setText("Class :");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel14.setText("Issuing City :");

        licNoTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        licNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licNoTxtFieldActionPerformed(evt);
            }
        });

        LicValidToTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicValidToTxtFieldActionPerformed(evt);
            }
        });

        IssuingCityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuingCityTxtFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel15.setText("Licence Details");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel16.setText("Credit Card No :");

        CreditCardNoTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        CreditCardNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditCardNoTxtFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel17.setText("Valid From :");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel18.setText("Valid To:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel19.setText("Provider :");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel21.setText("Middle Name :");

        middleNameTxtField3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        middleNameTxtField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameTxtField3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel6.setText("Address");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel22.setText("Street Name :");

        streetNameTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        streetNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameTxtFieldActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel23.setText("Apartment No :");

        apartmentNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartmentNoTxtFieldActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel24.setText("City :");

        cityTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtFieldActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel25.setText("State :");

        stateTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        stateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTxtFieldActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel26.setText("Zip :");

        zipTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        zipTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipTxtFieldActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel27.setText("Financials Accounts");
        jLabel27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel29.setText("Checking Acc No :");

        checkingAccNoTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        checkingAccNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingAccNoTxtFieldActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel30.setText("Created On :");

        checkCreatedOnTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        checkCreatedOnTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCreatedOnTxtFieldActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel32.setText("Credit :");

        checkingCreditTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        checkingCreditTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingCreditTxtFieldActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel33.setText("Debit :");

        checkDebitTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        checkDebitTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDebitTxtFieldActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel34.setText("Saving Acc No :");

        savingAccNoTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        savingAccNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingAccNoTxtFieldActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel35.setText("Created On :");

        savingCreatedOnTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        savingCreatedOnTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingCreatedOnTxtFieldActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel37.setText("Credit :");

        savingCreditTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        savingCreditTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingCreditTxtFieldActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel38.setText("Debit :");

        savingDebitTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        savingDebitTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingDebitTxtFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel20.setText("Active :");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel36.setText("Active :");

        checkActiveTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        checkActiveTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActiveTxtFieldActionPerformed(evt);
            }
        });

        savingActiveTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        savingActiveTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingActiveTxtFieldActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel39.setText("Active :");

        createPanelButton.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        createPanelButton.setText("Create");
        createPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPanelButtonActionPerformed(evt);
            }
        });

        pathTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTxtFieldActionPerformed(evt);
            }
        });

        AttachButton.setText("Attach");
        AttachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setText("Path:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(LicValidToTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(ClassTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(IssuingCityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CreditCardNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CCValidFromTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CCValidToTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cCProviderTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cCActiveTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(streetNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel23))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(checkingAccNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(checkingCreditTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(48, 48, 48)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel25)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(stateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel26))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel33)
                                                            .addComponent(jLabel30)
                                                            .addComponent(jLabel35)
                                                            .addComponent(jLabel38))
                                                        .addGap(29, 29, 29)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(checkCreatedOnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(checkDebitTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(savingCreatedOnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(savingDebitTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 0, Short.MAX_VALUE)))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(apartmentNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(zipTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(savingActiveTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(checkActiveTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addComponent(savingAccNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LicValidFromTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(DOBTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(phoneNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(middleNameTxtField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel5)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lastNameFieldTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(104, 104, 104)
                                                        .addComponent(Imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(licNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(75, 75, 75)
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(pathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AttachButton))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(savingCreditTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(145, 145, 145)
                                        .addComponent(createPanelButton))))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(middleNameTxtField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(lastNameFieldTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(DOBTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(phoneNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pathTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(AttachButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(licNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(LicValidFromTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(LicValidToTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(ClassTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(IssuingCityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(CreditCardNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CCValidFromTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(CCValidToTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(cCProviderTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)
                                .addComponent(cCActiveTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(streetNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(apartmentNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(stateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(zipTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(checkCreatedOnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(checkActiveTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkingAccNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(checkDebitTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkingCreditTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel34)
                                        .addComponent(savingAccNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(savingActiveTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel39)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(savingCreditTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savingCreatedOnTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(savingDebitTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addComponent(createPanelButton)
                        .addGap(59, 59, 59))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTxtFieldActionPerformed

    private void lastNameFieldTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldTxtfieldActionPerformed

    private void phoneNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoTxtFieldActionPerformed

    private void licNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licNoTxtFieldActionPerformed

    private void CreditCardNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditCardNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditCardNoTxtFieldActionPerformed

    private void middleNameTxtField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameTxtField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTxtField3ActionPerformed

    private void IssuingCityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuingCityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IssuingCityTxtFieldActionPerformed

    private void streetNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNameTxtFieldActionPerformed

    private void apartmentNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartmentNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apartmentNoTxtFieldActionPerformed

    private void cityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtFieldActionPerformed

    private void stateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTxtFieldActionPerformed

    private void zipTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipTxtFieldActionPerformed

    private void LicValidToTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicValidToTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicValidToTxtFieldActionPerformed

    private void checkingAccNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingAccNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingAccNoTxtFieldActionPerformed

    private void checkCreatedOnTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCreatedOnTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCreatedOnTxtFieldActionPerformed

    private void checkingCreditTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingCreditTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingCreditTxtFieldActionPerformed

    private void checkDebitTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDebitTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDebitTxtFieldActionPerformed

    private void savingAccNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingAccNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingAccNoTxtFieldActionPerformed

    private void savingCreatedOnTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingCreatedOnTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingCreatedOnTxtFieldActionPerformed

    private void savingCreditTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingCreditTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingCreditTxtFieldActionPerformed

    private void savingDebitTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingDebitTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingDebitTxtFieldActionPerformed

    private void checkActiveTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActiveTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkActiveTxtFieldActionPerformed

    private void savingActiveTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingActiveTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingActiveTxtFieldActionPerformed

    private void createPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPanelButtonActionPerformed
        // TODO add your handling code here:
        person.setFirstName(firstNameTxtField.getText());
        person.setMiddleName(middleNameTxtField3.getText());
        person.setLastName(lastNameFieldTxtfield.getText());
        person.setdOB(DOBTxtField.getText());
        person.setPhoneNo(phoneNoTxtField.getText());
        
      person.licence.setLicenceNo(licNoTxtField.getText());
        person.licence.setLicValidFrom(LicValidFromTxtField.getText());
        person.licence.setLicValidTo(LicValidToTxtField.getText());
        person.licence.setZclass(ClassTxtField.getText());
        person.licence.setIssuingBranch(IssuingCityTxtField.getText());
        
        person.creditcard.setCardNo(CreditCardNoTxtField.getText());
        person.creditcard.setCcValidFrom(CCValidFromTxtField.getText());
        person.creditcard.setCcValidTo(CCValidToTxtField.getText());
        person.creditcard.setCcActive(cCActiveTxtField.getText());
        person.creditcard.setCcprovider(cCProviderTxtField.getText());
        
        person.finanacc.setCheckingAcctNo(checkingAccNoTxtField.getText());
        person.finanacc.setCheckingCreatedOn(checkCreatedOnTxtField.getText());
        person.finanacc.setCheckingActive(checkActiveTxtField.getText());
        person.finanacc.setCheckingDebit(checkDebitTxtField.getText());
        person.finanacc.setCheckingCredit(checkingCreditTxtField.getText());
        
        person.finanacc.setSavingAcctNo(savingAccNoTxtField.getText());
        person.finanacc.setSavingCreatedOn(savingCreatedOnTxtField.getText());
        person.finanacc.setSavingActive(savingActiveTxtField.getText());
        person.finanacc.setSavingDebit(savingDebitTxtField.getText());
        person.finanacc.setSavingCredit(savingCreditTxtField.getText());
        
        person.address.setStreetAddress(streetNameTxtField.getText());
        person.address.setApartmentNo(apartmentNoTxtField.getText());
        person.address.setCity(cityTxtField.getText());
        person.address.setState(stateTxtField.getText());
        person.address.setZipCode(zipTxtField.getText());
        
        
        JOptionPane.showMessageDialog(null," User Created");
        firstNameTxtField.setText("");
        middleNameTxtField3.setText("");
        lastNameFieldTxtfield.setText("");
        DOBTxtField.setText("");
        phoneNoTxtField.setText("");
        licNoTxtField.setText("");
        LicValidFromTxtField.setText("");
        LicValidToTxtField.setText("");
        ClassTxtField.setText("");
        IssuingCityTxtField.setText("");
        CreditCardNoTxtField.setText("");
        CCValidFromTxtField.setText("");
        CCValidToTxtField.setText("");
        cCActiveTxtField.setText("");
        cCProviderTxtField.setText("");
        checkingAccNoTxtField.setText("");
        checkCreatedOnTxtField.setText("");
        checkActiveTxtField.setText("");
        checkDebitTxtField.setText("");
        checkingCreditTxtField.setText("");
        savingAccNoTxtField.setText("");
        savingCreatedOnTxtField.setText("");
        savingActiveTxtField.setText("");
        savingDebitTxtField.setText("");
        savingCreditTxtField.setText("");
        streetNameTxtField.setText("");
        apartmentNoTxtField.setText("");
        cityTxtField.setText("");
        stateTxtField.setText("");
        zipTxtField.setText("");
        
        
    }//GEN-LAST:event_createPanelButtonActionPerformed

    private void pathTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTxtFieldActionPerformed

    private void AttachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachButtonActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        person.setFilename(f.getAbsolutePath());
        pathTxtField.setText(person.getFilename());
        ImageIcon icon=new ImageIcon(person.getFilename());
        Imagelabel.setIcon(icon);

    }//GEN-LAST:event_AttachButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttachButton;
    private javax.swing.JTextField CCValidFromTxtField;
    private javax.swing.JTextField CCValidToTxtField;
    private javax.swing.JTextField ClassTxtField;
    private javax.swing.JTextField CreditCardNoTxtField;
    private javax.swing.JTextField DOBTxtField;
    private javax.swing.JLabel Imagelabel;
    private javax.swing.JTextField IssuingCityTxtField;
    private javax.swing.JTextField LicValidFromTxtField;
    private javax.swing.JTextField LicValidToTxtField;
    private javax.swing.JTextField apartmentNoTxtField;
    private javax.swing.JTextField cCActiveTxtField;
    private javax.swing.JTextField cCProviderTxtField;
    private javax.swing.JTextField checkActiveTxtField;
    private javax.swing.JTextField checkCreatedOnTxtField;
    private javax.swing.JTextField checkDebitTxtField;
    private javax.swing.JTextField checkingAccNoTxtField;
    private javax.swing.JTextField checkingCreditTxtField;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JButton createPanelButton;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameFieldTxtfield;
    private javax.swing.JTextField licNoTxtField;
    private javax.swing.JTextField middleNameTxtField3;
    private javax.swing.JTextField pathTxtField;
    private javax.swing.JTextField phoneNoTxtField;
    private javax.swing.JTextField savingAccNoTxtField;
    private javax.swing.JTextField savingActiveTxtField;
    private javax.swing.JTextField savingCreatedOnTxtField;
    private javax.swing.JTextField savingCreditTxtField;
    private javax.swing.JTextField savingDebitTxtField;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JTextField streetNameTxtField;
    private javax.swing.JTextField zipTxtField;
    // End of variables declaration//GEN-END:variables
}
