/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import javax.swing.ImageIcon;

/**
 *
 * @author cheta
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    public ViewJPanel(Person person) {
        initComponents();
        displayPerson(person);
    }
    
    private void displayPerson(Person person){
        
       String personfirstname = person.getFirstName();
        firstNameTxtField.setText(personfirstname);
        
        String personmiddlename = person.getMiddleName();
        middleNameTxtField3.setText(personmiddlename);
        
        String personLastname = person.getLastName();
        lastNameFieldTxtfield.setText(personLastname);
        
        String persondob = person.getdOB();
        DOBTxtField.setText(persondob);
       
        String personphoneno = person.getPhoneNo();
        phoneNoTxtField.setText(personphoneno);
        
        String personlicenceno = person.licence.getLicenceNo();
        licNoTxtField.setText(personlicenceno);
        
        String personlicencevalidfrom = person.licence.getLicValidFrom();
        LicValidFromTxtField.setText(personlicencevalidfrom);
        
        String personlicencevalidto = person.licence.getLicValidTo();
        LicValidToTxtField.setText(personlicencevalidto);
        
        String personclass = person.licence.getZclass();
        ClassTxtField.setText(personclass);
        
        String personissuingbranch = person.licence.getIssuingBranch();
        IssuingCityTxtField.setText(personissuingbranch);
        
        
        
        String personcreditcardno = person.creditcard.getCardNo();
        CreditCardNoTxtField.setText(personcreditcardno);
        
        String creditcardvalidfrom = person.creditcard.getCcValidFrom();
        CCValidFromTxtField.setText(creditcardvalidfrom);
        
        String creditcardvalidto = person.creditcard.getCcValidTo();
        CCValidToTxtField.setText(creditcardvalidto);
        
        String creditcardactive = person.creditcard.getCcActive();
        cCActiveTxtField.setText(creditcardactive);
        
        String creditardprovider = person.creditcard.getCcprovider();
        cCProviderTxtField.setText(creditardprovider);
        
        
        
        String addressstreet = person.address.getStreetAddress();
        streetNameTxtField.setText(addressstreet);
        
        String addressapt = person.address.getApartmentNo();
        apartmentNoTxtField.setText(addressapt);
        
        String addresscity = person.address.getCity();
        cityTxtField.setText(addresscity);
        
        String addressstate = person.address.getState();
        stateTxtField.setText(addressstate);
        
        String addresszip = person.address.getZipCode();
        zipTxtField.setText(addresszip);
        
        
        
        String checkingaccno = person.finanacc.getCheckingAcctNo();
        checkingAccNoTxtField.setText(checkingaccno);
        
        String checkingcreatedon = person.finanacc.getCheckingCreatedOn();
        checkCreatedOnTxtField.setText(checkingcreatedon);
        
        String checkingactive = person.finanacc.getCheckingActive();
        checkingActiveTxtField.setText(checkingactive);
        
        String checkingdebit = person.finanacc.getCheckingDebit();
        checkDebitTxtField.setText(checkingdebit);
        
        String checkingcredit = person.finanacc.getCheckingCredit();
        checkingCreditTxtField.setText(checkingcredit);
        
        
        String savingaccno = person.finanacc.getSavingAcctNo();
        savingAccNoTxtField.setText(savingaccno);
        
        String savingcreatedon = person.finanacc.getSavingCreatedOn();
        savingCreatedOnTxtField.setText(savingcreatedon);
        
        String savingactive = person.finanacc.getSavingActive();
        savingActiveTxtField.setText(savingactive);
        
        String savingdebit = person.finanacc.getSavingDebit();
        savingDebitTxtField.setText(savingdebit);
        
        String savingcredit = person.finanacc.getSavingCredit();
        savingCreditTxtField.setText(savingcredit);
        
        ImageIcon icon=new ImageIcon(person.getFilename());
        Labeltext.setIcon(icon);
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstNameTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lastNameFieldTxtfield = new javax.swing.JTextField();
        DOBTxtField = new javax.swing.JTextField();
        phoneNoTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        licNoTxtField = new javax.swing.JTextField();
        LicValidToTxtField = new javax.swing.JTextField();
        LicValidFromTxtField = new javax.swing.JTextField();
        ClassTxtField = new javax.swing.JTextField();
        IssuingCityTxtField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CreditCardNoTxtField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CCValidFromTxtField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        CCValidToTxtField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cCProviderTxtField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cCActiveTxtField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        middleNameTxtField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        streetNameTxtField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        apartmentNoTxtField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cityTxtField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        stateTxtField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        zipTxtField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        checkingAccNoTxtField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        checkCreatedOnTxtField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        checkingActiveTxtField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        checkingCreditTxtField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        checkDebitTxtField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        savingAccNoTxtField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        savingCreatedOnTxtField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        savingActiveTxtField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        savingCreditTxtField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        savingDebitTxtField = new javax.swing.JTextField();
        Labeltext = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("View User Profile Information");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel3.setText("Credit Card Details");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setText("First Name:");

        firstNameTxtField.setBackground(new java.awt.Color(255, 204, 102));
        firstNameTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        firstNameTxtField.setBorder(null);
        firstNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setText("Last Name :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel7.setText("Phone No :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel8.setText("D.O.B :");

        lastNameFieldTxtfield.setBackground(new java.awt.Color(255, 204, 102));
        lastNameFieldTxtfield.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lastNameFieldTxtfield.setBorder(null);
        lastNameFieldTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldTxtfieldActionPerformed(evt);
            }
        });

        DOBTxtField.setBackground(new java.awt.Color(255, 204, 102));
        DOBTxtField.setBorder(null);

        phoneNoTxtField.setBackground(new java.awt.Color(255, 204, 102));
        phoneNoTxtField.setBorder(null);
        phoneNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoTxtFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel9.setText("Personal Details");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel10.setText("Valid From :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel11.setText("Licence No :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel12.setText("Valid To:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel13.setText("Class :");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel14.setText("Issuing City :");

        licNoTxtField.setBackground(new java.awt.Color(255, 204, 102));
        licNoTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        licNoTxtField.setBorder(null);
        licNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licNoTxtFieldActionPerformed(evt);
            }
        });

        LicValidToTxtField.setBackground(new java.awt.Color(255, 204, 102));
        LicValidToTxtField.setBorder(null);
        LicValidToTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicValidToTxtFieldActionPerformed(evt);
            }
        });

        LicValidFromTxtField.setBackground(new java.awt.Color(255, 204, 102));
        LicValidFromTxtField.setBorder(null);

        ClassTxtField.setBackground(new java.awt.Color(255, 204, 102));
        ClassTxtField.setBorder(null);

        IssuingCityTxtField.setBackground(new java.awt.Color(255, 204, 102));
        IssuingCityTxtField.setBorder(null);
        IssuingCityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuingCityTxtFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel15.setText("Licence Details");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel16.setText("Credit Card No :");

        CreditCardNoTxtField.setBackground(new java.awt.Color(255, 204, 102));
        CreditCardNoTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        CreditCardNoTxtField.setBorder(null);
        CreditCardNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditCardNoTxtFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel17.setText("Valid From :");

        CCValidFromTxtField.setBackground(new java.awt.Color(255, 204, 102));
        CCValidFromTxtField.setBorder(null);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel18.setText("Valid To:");

        CCValidToTxtField.setBackground(new java.awt.Color(255, 204, 102));
        CCValidToTxtField.setBorder(null);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel19.setText("Provider :");

        cCProviderTxtField.setBackground(new java.awt.Color(255, 204, 102));
        cCProviderTxtField.setBorder(null);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel20.setText("Active :");

        cCActiveTxtField.setBackground(new java.awt.Color(255, 204, 102));
        cCActiveTxtField.setBorder(null);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel21.setText("Middle Name :");

        middleNameTxtField3.setBackground(new java.awt.Color(255, 204, 102));
        middleNameTxtField3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        middleNameTxtField3.setBorder(null);
        middleNameTxtField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameTxtField3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel6.setText("Address");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel22.setText("Street Name :");

        streetNameTxtField.setBackground(new java.awt.Color(255, 204, 102));
        streetNameTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        streetNameTxtField.setBorder(null);
        streetNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameTxtFieldActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel23.setText("Apartment No :");

        apartmentNoTxtField.setBackground(new java.awt.Color(255, 204, 102));
        apartmentNoTxtField.setBorder(null);
        apartmentNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartmentNoTxtFieldActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel24.setText("City :");

        cityTxtField.setBackground(new java.awt.Color(255, 204, 102));
        cityTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cityTxtField.setBorder(null);
        cityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtFieldActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel25.setText("State :");

        stateTxtField.setBackground(new java.awt.Color(255, 204, 102));
        stateTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        stateTxtField.setBorder(null);
        stateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTxtFieldActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel26.setText("Zip :");

        zipTxtField.setBackground(new java.awt.Color(255, 204, 102));
        zipTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        zipTxtField.setBorder(null);
        zipTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipTxtFieldActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel27.setText("Financials Accounts");
        jLabel27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel29.setText("Checking Acc No :");

        checkingAccNoTxtField.setBackground(new java.awt.Color(255, 204, 102));
        checkingAccNoTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        checkingAccNoTxtField.setBorder(null);
        checkingAccNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingAccNoTxtFieldActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel30.setText("Created On :");

        checkCreatedOnTxtField.setBackground(new java.awt.Color(255, 204, 102));
        checkCreatedOnTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        checkCreatedOnTxtField.setBorder(null);
        checkCreatedOnTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCreatedOnTxtFieldActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel31.setText("Active :");

        checkingActiveTxtField.setBackground(new java.awt.Color(255, 204, 102));
        checkingActiveTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        checkingActiveTxtField.setBorder(null);
        checkingActiveTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingActiveTxtFieldActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel32.setText("Credit :");

        checkingCreditTxtField.setBackground(new java.awt.Color(255, 204, 102));
        checkingCreditTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        checkingCreditTxtField.setBorder(null);
        checkingCreditTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingCreditTxtFieldActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel33.setText("Debit :");

        checkDebitTxtField.setBackground(new java.awt.Color(255, 204, 102));
        checkDebitTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        checkDebitTxtField.setBorder(null);
        checkDebitTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDebitTxtFieldActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel34.setText("Saving Acc No :");

        savingAccNoTxtField.setBackground(new java.awt.Color(255, 204, 102));
        savingAccNoTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        savingAccNoTxtField.setBorder(null);
        savingAccNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingAccNoTxtFieldActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel35.setText("Created On :");

        savingCreatedOnTxtField.setBackground(new java.awt.Color(255, 204, 102));
        savingCreatedOnTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        savingCreatedOnTxtField.setBorder(null);
        savingCreatedOnTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingCreatedOnTxtFieldActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel36.setText("Active :");

        savingActiveTxtField.setBackground(new java.awt.Color(255, 204, 102));
        savingActiveTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        savingActiveTxtField.setBorder(null);
        savingActiveTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingActiveTxtFieldActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel37.setText("Credit :");

        savingCreditTxtField.setBackground(new java.awt.Color(255, 204, 102));
        savingCreditTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        savingCreditTxtField.setBorder(null);
        savingCreditTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingCreditTxtFieldActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel38.setText("Debit :");

        savingDebitTxtField.setBackground(new java.awt.Color(255, 204, 102));
        savingDebitTxtField.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        savingDebitTxtField.setBorder(null);
        savingDebitTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingDebitTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(licNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(324, 324, 324)
                                .addComponent(Labeltext, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel31)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(LicValidFromTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69)
                                                .addComponent(jLabel12)
                                                .addGap(23, 23, 23)
                                                .addComponent(LicValidToTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel13)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(ClassTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(cCProviderTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkingActiveTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(savingActiveTxtField)
                                    .addComponent(zipTxtField)
                                    .addComponent(cCActiveTxtField)
                                    .addComponent(IssuingCityTxtField))))))
                .addContainerGap(539, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DOBTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(phoneNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(middleNameTxtField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameFieldTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel34)
                            .addComponent(jLabel32)
                            .addComponent(jLabel29)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CCValidFromTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(CCValidToTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CreditCardNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(streetNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(checkingAccNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkingCreditTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(savingAccNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(savingCreditTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18)
                                        .addComponent(apartmentNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel38)
                                            .addComponent(jLabel25))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(checkDebitTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(checkCreatedOnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(savingCreatedOnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(savingDebitTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(stateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(middleNameTxtField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(lastNameFieldTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(DOBTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(phoneNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(licNoTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(LicValidFromTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(LicValidToTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(ClassTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(IssuingCityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(CreditCardNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CCValidFromTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(CCValidToTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(cCProviderTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)
                                .addComponent(cCActiveTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(streetNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(apartmentNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(stateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(zipTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)))
                        .addComponent(jLabel27)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(checkingAccNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(checkingActiveTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkCreatedOnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(checkingCreditTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(checkDebitTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(savingAccNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(savingActiveTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savingCreatedOnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(savingCreditTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(savingDebitTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Labeltext, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void savingCreatedOnTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingCreatedOnTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingCreatedOnTxtFieldActionPerformed

    private void savingAccNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingAccNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingAccNoTxtFieldActionPerformed

    private void checkDebitTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDebitTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDebitTxtFieldActionPerformed

    private void checkingCreditTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingCreditTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingCreditTxtFieldActionPerformed

    private void checkingActiveTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingActiveTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingActiveTxtFieldActionPerformed

    private void LicValidToTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicValidToTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicValidToTxtFieldActionPerformed

    private void licNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licNoTxtFieldActionPerformed

    private void phoneNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoTxtFieldActionPerformed

    private void lastNameFieldTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldTxtfieldActionPerformed

    private void checkCreatedOnTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCreatedOnTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCreatedOnTxtFieldActionPerformed

    private void checkingAccNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingAccNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingAccNoTxtFieldActionPerformed

    private void firstNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTxtFieldActionPerformed

    private void zipTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipTxtFieldActionPerformed

    private void stateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTxtFieldActionPerformed

    private void cityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtFieldActionPerformed

    private void apartmentNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartmentNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apartmentNoTxtFieldActionPerformed

    private void streetNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNameTxtFieldActionPerformed

    private void middleNameTxtField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameTxtField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTxtField3ActionPerformed

    private void savingDebitTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingDebitTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingDebitTxtFieldActionPerformed

    private void savingCreditTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingCreditTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingCreditTxtFieldActionPerformed

    private void savingActiveTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingActiveTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingActiveTxtFieldActionPerformed

    private void CreditCardNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditCardNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditCardNoTxtFieldActionPerformed

    private void IssuingCityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuingCityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IssuingCityTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCValidFromTxtField;
    private javax.swing.JTextField CCValidToTxtField;
    private javax.swing.JTextField ClassTxtField;
    private javax.swing.JTextField CreditCardNoTxtField;
    private javax.swing.JTextField DOBTxtField;
    private javax.swing.JTextField IssuingCityTxtField;
    private javax.swing.JLabel Labeltext;
    private javax.swing.JTextField LicValidFromTxtField;
    private javax.swing.JTextField LicValidToTxtField;
    private javax.swing.JTextField apartmentNoTxtField;
    private javax.swing.JTextField cCActiveTxtField;
    private javax.swing.JTextField cCProviderTxtField;
    private javax.swing.JTextField checkCreatedOnTxtField;
    private javax.swing.JTextField checkDebitTxtField;
    private javax.swing.JTextField checkingAccNoTxtField;
    private javax.swing.JTextField checkingActiveTxtField;
    private javax.swing.JTextField checkingCreditTxtField;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameFieldTxtfield;
    private javax.swing.JTextField licNoTxtField;
    private javax.swing.JTextField middleNameTxtField3;
    private javax.swing.JTextField phoneNoTxtField;
    private javax.swing.JTextField savingAccNoTxtField;
    private javax.swing.JTextField savingActiveTxtField;
    private javax.swing.JTextField savingCreatedOnTxtField;
    private javax.swing.JTextField savingCreditTxtField;
    private javax.swing.JTextField savingDebitTxtField;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JTextField streetNameTxtField;
    private javax.swing.JTextField zipTxtField;
    // End of variables declaration//GEN-END:variables
}
