/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.*;
import javax.swing.JOptionPane;

/**
 *
 * @author cheta
 */
public class AddFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddFlightJPanel
     */
    private JPanel UserProcessContainer;
    private TravelAgency travelagency;
//    private Flight flight;
//    private Airline airline;
//    public AddFlightJPanel() {
//        
//    }

    AddFlightJPanel(JPanel UserProcessContainer,TravelAgency travelagency) {
        initComponents();
        this.UserProcessContainer=UserProcessContainer;
        this.travelagency=travelagency;
        initilizeselectAirlinerComboBox();
    }
    
    
    public void initilizeselectAirlinerComboBox() {
        selectAirlineComboBox.removeAllItems();
        for (Airline airline : travelagency.getAirlinerDirectory()) {
            selectAirlineComboBox.addItem(airline);
        }
    }

//    AddFlightJPanel(JPanel UserProcessContainer) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flightIDtxtfld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        capacitynewFlighttxtfld = new javax.swing.JTextField();
        addnewFlightButton = new javax.swing.JButton();
        backCreateNewFlightBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sourcenewFlighttxtfld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        destinationnewFlighttxtfld1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        timeOfTheDayTextField = new javax.swing.JTextField();
        selectAirlineComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Create New Flight");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Airline Name :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Flight ID :");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        flightIDtxtfld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Capacity :");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        capacitynewFlighttxtfld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        addnewFlightButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addnewFlightButton.setText("Add");
        addnewFlightButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addnewFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewFlightButtonActionPerformed(evt);
            }
        });

        backCreateNewFlightBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backCreateNewFlightBtn.setText(">> Back");
        backCreateNewFlightBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backCreateNewFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backCreateNewFlightBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Source :");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sourcenewFlighttxtfld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Destination :");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        destinationnewFlighttxtfld1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Time Of the Day :");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        timeOfTheDayTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Please enter either Morning, AfterNoon or Evening");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(28, 28, 28)
                                        .addComponent(timeOfTheDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(flightIDtxtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(sourcenewFlighttxtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(selectAirlineComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(28, 28, 28)
                                        .addComponent(destinationnewFlighttxtfld1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8))))
                        .addComponent(capacitynewFlighttxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(backCreateNewFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(306, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addnewFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectAirlineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(flightIDtxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(capacitynewFlighttxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sourcenewFlighttxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(destinationnewFlighttxtfld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(timeOfTheDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(23, 23, 23)
                .addComponent(addnewFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(backCreateNewFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backCreateNewFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backCreateNewFlightBtnActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
        
    }//GEN-LAST:event_backCreateNewFlightBtnActionPerformed

    private void addnewFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewFlightButtonActionPerformed
        // TODO add your handling code here:
        if (validData()){
      Airline airline = (Airline) selectAirlineComboBox.getSelectedItem();
       String flightID = flightIDtxtfld.getText();
       int capacity = Integer.parseInt(capacitynewFlighttxtfld.getText());
       String source = sourcenewFlighttxtfld.getText();
       String destination = destinationnewFlighttxtfld1.getText();
       String timeoftheday = timeOfTheDayTextField.getText();
       
       Flight flight = new Flight(flightID, capacity, source, destination, airline, timeoftheday);
       airline.getFlight().add(flight);
       
        JOptionPane.showMessageDialog(null, "Flight Details added successfully");
        
        flightIDtxtfld.setText("");
        capacitynewFlighttxtfld.setText("");
        sourcenewFlighttxtfld.setText("");
        destinationnewFlighttxtfld1.setText("");
        timeOfTheDayTextField.setText("");
        
        }
    }//GEN-LAST:event_addnewFlightButtonActionPerformed
       
    
    private boolean validData() {
        //To change body of generated methods, choose Tools | Templates.
        if(flightIDtxtfld.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Flight ID..");
            return false;
        }
        
        if(capacitynewFlighttxtfld.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Total Capacity of the flight.");
            return false;
        }
        
        if(sourcenewFlighttxtfld.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Flight's Source..");
            return false;
        }
        
        if(destinationnewFlighttxtfld1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Flight's Destination..");
            return false;
        }
        
        if(timeOfTheDayTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Time of the Day..");
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnewFlightButton;
    private javax.swing.JButton backCreateNewFlightBtn;
    private javax.swing.JTextField capacitynewFlighttxtfld;
    private javax.swing.JTextField destinationnewFlighttxtfld1;
    private javax.swing.JTextField flightIDtxtfld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox selectAirlineComboBox;
    private javax.swing.JTextField sourcenewFlighttxtfld;
    private javax.swing.JTextField timeOfTheDayTextField;
    // End of variables declaration//GEN-END:variables
}
