/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cheta
 */
public class ManageAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinerJPanel
     */
    private JPanel UserProcessContainer;
    private TravelAgency travelagency;
    

    ManageAirlinerJPanel(JPanel UserProcessContainer,TravelAgency travelagency) {
       initComponents();
        this.UserProcessContainer=UserProcessContainer;
        this.travelagency=travelagency;
        //this.airline=airline;
        populatetable();
        initilizeselectAirlinerComboBox();
    }
    
    public void initilizeselectAirlinerComboBox() {
        selectAirlineComboBox.removeAllItems();
        for (Airline airline : travelagency.getAirlinerDirectory()) {
            selectAirlineComboBox.addItem(airline);
        }
    }
    
    private void populatetable()
    {
        DefaultTableModel dtm = (DefaultTableModel) viewAirlinerjTable.getModel();
        dtm.setRowCount(0);
        
        for(Airline airline : travelagency.getAirlinerDirectory()){
            for(Flight flight : airline.getFlight())
            {
                Object row[] = new Object [6];
                row[0] = airline;
                row[1] = flight.getFlightId();
                row[2]=flight.getSource();
                row[3] = flight.getDestination();
                row[4]= flight.getCapacity();
                row[5]=flight.getTimeoftheday();
                
                
                dtm.addRow(row);
                
                
            }
       
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewAirlinerjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchManageAirlinerjButton = new javax.swing.JButton();
        createManageAirlinerjButton = new javax.swing.JButton();
        backManageAirlinerjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchAirlinerjTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        selectAirlineComboBox = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Manage Airlines");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        viewAirlinerjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline name", "Flight ID", "Source", "Destination", "Capacity", "Time of the day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewAirlinerjTable);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Airline :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        searchManageAirlinerjButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchManageAirlinerjButton.setText("Search");
        searchManageAirlinerjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchManageAirlinerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchManageAirlinerjButtonActionPerformed(evt);
            }
        });

        createManageAirlinerjButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        createManageAirlinerjButton.setText("Create New Airline");
        createManageAirlinerjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        createManageAirlinerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createManageAirlinerjButtonActionPerformed(evt);
            }
        });

        backManageAirlinerjButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backManageAirlinerjButton.setText(">>Back");
        backManageAirlinerjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backManageAirlinerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backManageAirlinerjButtonActionPerformed(evt);
            }
        });

        searchAirlinerjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Flight ID", "Source", "Destination", "Capcaity", "Time of the day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(searchAirlinerjTable);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Searched Airlines");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(selectAirlineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(searchManageAirlinerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(createManageAirlinerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(backManageAirlinerjButton)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createManageAirlinerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchManageAirlinerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectAirlineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(backManageAirlinerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createManageAirlinerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createManageAirlinerjButtonActionPerformed
        // TODO add your handling code here:
        createAirlineJPanel accountpanel = new createAirlineJPanel(UserProcessContainer,travelagency);
        UserProcessContainer.add("ViewAirlinerJPanel", accountpanel);
        CardLayout layout = (CardLayout)UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_createManageAirlinerjButtonActionPerformed

    private void backManageAirlinerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backManageAirlinerjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_backManageAirlinerjButtonActionPerformed

    private void searchManageAirlinerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchManageAirlinerjButtonActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel)searchAirlinerjTable.getModel();
        dtm.setRowCount(0);
        
        for(Airline airline : travelagency.getAirlinerDirectory())
        {
            for(Flight flight : airline.getFlight())
            {
            if(airline.getAirlineName().equalsIgnoreCase(jTextField1.getText()))
            {
                Object row[] = new Object [6];
                row[0] = airline;
                row[1] = flight.getFlightId();
                row[2]=flight.getSource();
                row[3] = flight.getDestination();
                row[4]= flight.getCapacity();
                row[5]=flight.getTimeoftheday();
                
                
                dtm.addRow(row);
            }
        }
        }
        
        
    }//GEN-LAST:event_searchManageAirlinerjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backManageAirlinerjButton;
    private javax.swing.JButton createManageAirlinerjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable searchAirlinerjTable;
    private javax.swing.JButton searchManageAirlinerjButton;
    private javax.swing.JComboBox selectAirlineComboBox;
    private javax.swing.JTable viewAirlinerjTable;
    // End of variables declaration//GEN-END:variables
}
