/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Fleet;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cheta
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Fleet fleet;
    public MainJFrame() throws IOException {
        initComponents();
        fleet = new Fleet();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        viewFleetBTN = new javax.swing.JButton();
        newEntryBTN = new javax.swing.JButton();
        firstAvailBTN = new javax.swing.JButton();
        boeingBTN = new javax.swing.JButton();
        serialNoSearchBTN = new javax.swing.JButton();
        modelManSearchBTN = new javax.swing.JButton();
        seatsAvailableBTN = new javax.swing.JButton();
        listAvailBTN = new javax.swing.JButton();
        listExpiredBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("   Fleet Catalog   ");

        viewFleetBTN.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        viewFleetBTN.setText("View Fleet");
        viewFleetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFleetBTNActionPerformed(evt);
            }
        });

        newEntryBTN.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        newEntryBTN.setText("New Entry to Catalog");
        newEntryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEntryBTNActionPerformed(evt);
            }
        });

        firstAvailBTN.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        firstAvailBTN.setText("1st Available Plane/Available");
        firstAvailBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstAvailBTNActionPerformed(evt);
            }
        });

        boeingBTN.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        boeingBTN.setText("Boeing Airplanes");
        boeingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boeingBTNActionPerformed(evt);
            }
        });

        serialNoSearchBTN.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        serialNoSearchBTN.setText("Search by Serial no");
        serialNoSearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNoSearchBTNActionPerformed(evt);
            }
        });

        modelManSearchBTN.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        modelManSearchBTN.setText("Search by Model/Manfd Year");
        modelManSearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelManSearchBTNActionPerformed(evt);
            }
        });

        seatsAvailableBTN.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        seatsAvailableBTN.setText("Available Plane based on Seats");
        seatsAvailableBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsAvailableBTNActionPerformed(evt);
            }
        });

        listAvailBTN.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        listAvailBTN.setText("List of available Airplanes");
        listAvailBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAvailBTNActionPerformed(evt);
            }
        });

        listExpiredBTN.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        listExpiredBTN.setText("List of expired Cert Airplanes");
        listExpiredBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listExpiredBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstAvailBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boeingBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modelManSearchBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serialNoSearchBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewFleetBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatsAvailableBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listAvailBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listExpiredBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newEntryBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(viewFleetBTN)
                .addGap(58, 58, 58)
                .addComponent(newEntryBTN)
                .addGap(71, 71, 71)
                .addComponent(firstAvailBTN)
                .addGap(83, 83, 83)
                .addComponent(boeingBTN)
                .addGap(91, 91, 91)
                .addComponent(serialNoSearchBTN)
                .addGap(92, 92, 92)
                .addComponent(modelManSearchBTN)
                .addGap(78, 78, 78)
                .addComponent(seatsAvailableBTN)
                .addGap(89, 89, 89)
                .addComponent(listAvailBTN)
                .addGap(81, 81, 81)
                .addComponent(listExpiredBTN)
                .addGap(55, 55, 55))
        );

        SplitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(jPanel2);

        getContentPane().add(SplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewFleetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFleetBTNActionPerformed
        // TODO add your handling code here:
        ViewFleetPanel viewfleetpanel = new ViewFleetPanel(fleet);
        SplitPane.setRightComponent(viewfleetpanel);
    }//GEN-LAST:event_viewFleetBTNActionPerformed

    private void newEntryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEntryBTNActionPerformed
        // TODO add your handling code here:
        CreateJPanel createjpanel = new CreateJPanel(fleet);
        SplitPane.setRightComponent(createjpanel);
    }//GEN-LAST:event_newEntryBTNActionPerformed

    private void firstAvailBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstAvailBTNActionPerformed
        // TODO add your handling code here:
        LatestPlanePanel latestpanel = new LatestPlanePanel(fleet);
        SplitPane.setRightComponent(latestpanel);
    }//GEN-LAST:event_firstAvailBTNActionPerformed

    private void boeingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boeingBTNActionPerformed
        // TODO add your handling code here:
        BoeingJpanel boeingjpanel = new BoeingJpanel(fleet);
        SplitPane.setRightComponent(boeingjpanel);
    }//GEN-LAST:event_boeingBTNActionPerformed

    private void serialNoSearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNoSearchBTNActionPerformed
        // TODO add your handling code here:
        SerialNumberJPanel serialnumberjpanel = new SerialNumberJPanel(fleet);
        SplitPane.setRightComponent(serialnumberjpanel);
    }//GEN-LAST:event_serialNoSearchBTNActionPerformed

    private void modelManSearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelManSearchBTNActionPerformed
        // TODO add your handling code here:
        SearchModelJPanel searchmodeljpanel = new SearchModelJPanel(fleet);
        SplitPane.setRightComponent(searchmodeljpanel);
    }//GEN-LAST:event_modelManSearchBTNActionPerformed

    private void seatsAvailableBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsAvailableBTNActionPerformed
        // TODO add your handling code here:
        SeatsAvailablePlaneJPanel seatsavailablejpanel = new SeatsAvailablePlaneJPanel(fleet);
        SplitPane.setRightComponent(seatsavailablejpanel);
    }//GEN-LAST:event_seatsAvailableBTNActionPerformed

    private void listAvailBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAvailBTNActionPerformed
        // TODO add your handling code here:
        ListAvailablePlanes listavailablepanel = new ListAvailablePlanes(fleet);
        SplitPane.setRightComponent(listavailablepanel);
        
    }//GEN-LAST:event_listAvailBTNActionPerformed

    private void listExpiredBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listExpiredBTNActionPerformed
        // TODO add your handling code here:
        ExpiredCertificateJPanel expiredcertificatejpanel = new ExpiredCertificateJPanel(fleet);
        SplitPane.setRightComponent(expiredcertificatejpanel);
    }//GEN-LAST:event_listExpiredBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MainJFrame().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton boeingBTN;
    private javax.swing.JButton firstAvailBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton listAvailBTN;
    private javax.swing.JButton listExpiredBTN;
    private javax.swing.JButton modelManSearchBTN;
    private javax.swing.JButton newEntryBTN;
    private javax.swing.JButton seatsAvailableBTN;
    private javax.swing.JButton serialNoSearchBTN;
    private javax.swing.JButton viewFleetBTN;
    // End of variables declaration//GEN-END:variables
}
