/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Fleet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Business.Airplane;


/**
 *
 * @author cheta
 */
public class ViewFleetPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFleetPanel
     */
    private Fleet fleet;

    private Airplane airplane;
    public ViewFleetPanel(Fleet fleet) {
        initComponents();
        this.fleet=fleet;
        displaytable();
        
    }
    
    private void displaytable() {
        DefaultTableModel dtm = (DefaultTableModel)viewFleetTable.getModel();
        dtm.setRowCount(0);
        for(Airplane vs : fleet.getFleet())
        {
            
            Object row[]= new Object[8];
            row [0] = vs;
            row [1] = vs.getModelNumber();
            row [2] = vs.getDepartureTime();
            row [3] = vs.getManufacturer();
            row [4] = vs.getManufacturedYear();
            row [5] = vs.getCapacity();
            row [6] = vs.getValidity();
            
            dtm.addRow(row);
        }
    }

    ViewFleetPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

//    private void displayTable(){
//        
//        
//    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewFleetTable = new javax.swing.JTable();
        fleetViewButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serialNoTextFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        modelNoTextFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        departureTimeTextFld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        manufacturedByTextFld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        manufacturedYearTextFld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        airplaneCapacityTextFld = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        certificateTextFld = new javax.swing.JTextField();
        updatejButton = new javax.swing.JButton();
        savejButton = new javax.swing.JButton();

        viewFleetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Model Number", "Departure Time", "Manufacturerl", "Manufactured Year", "Capacity", "Valid Till"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewFleetTable);

        fleetViewButton.setText("View");
        fleetViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fleetViewButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("      View Fleet Catalog");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("   Serial Number :");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        serialNoTextFld.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        serialNoTextFld.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("   Model Number :");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        modelNoTextFld.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        modelNoTextFld.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("  Departure Time:");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        departureTimeTextFld.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        departureTimeTextFld.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText(" Manufactured By :");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        manufacturedByTextFld.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        manufacturedByTextFld.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("Manufactured Year :");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        manufacturedYearTextFld.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        manufacturedYearTextFld.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setText("Airplane Capacity :");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        airplaneCapacityTextFld.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        airplaneCapacityTextFld.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel8.setText("Certificate Validity :");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        certificateTextFld.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        certificateTextFld.setEnabled(false);

        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        savejButton.setText("Save");
        savejButton.setEnabled(false);
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 619, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(airplaneCapacityTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departureTimeTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelNoTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serialNoTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manufacturedByTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manufacturedYearTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(85, 85, 85)
                        .addComponent(certificateTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1341, 1341, 1341))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(fleetViewButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1083, 1083, 1083)
                        .addComponent(updatejButton)
                        .addGap(45, 45, 45)
                        .addComponent(savejButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fleetViewButton)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(serialNoTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(modelNoTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(departureTimeTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(manufacturedByTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(manufacturedYearTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(airplaneCapacityTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(certificateTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatejButton)
                    .addComponent(savejButton))
                .addGap(167, 167, 167))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fleetViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fleetViewButtonActionPerformed
        // TODO add your handling code here:
        int selectedrow = viewFleetTable.getSelectedRow();
        
        if (selectedrow >= 0)
        {
            Airplane A = (Airplane)viewFleetTable.getValueAt(selectedrow, 0);
            serialNoTextFld.setText(A.getSerialNumber());
            modelNoTextFld.setText(A.getModelNumber());
            departureTimeTextFld.setText(A.getDepartureTime());
            manufacturedByTextFld.setText(A.getManufacturer());
            manufacturedYearTextFld.setText(A.getManufacturedYear());
            airplaneCapacityTextFld.setText(A.getCapacity());
            certificateTextFld.setText(A.getValidity());
            
        }
        else
            JOptionPane.showMessageDialog(null,"please select any row to proceed");
           
       
    }//GEN-LAST:event_fleetViewButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        // TODO add your handling code here:
            serialNoTextFld.setEnabled(true);
            modelNoTextFld.setEnabled(true);
            departureTimeTextFld.setEnabled(true);
            manufacturedByTextFld.setEnabled(true);
            manufacturedYearTextFld.setEnabled(true);
            airplaneCapacityTextFld.setEnabled(true);
            certificateTextFld.setEnabled(true);
            savejButton.setEnabled(true);
            updatejButton.setEnabled(false);
        
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
    if (validData()){
        int selectedrow = viewFleetTable.getSelectedRow();
        Airplane A = (Airplane)viewFleetTable.getValueAt(selectedrow, 0);
        String modelnumber = modelNoTextFld.getText();
        String serialnumber = serialNoTextFld.getText();
        String departuretime = departureTimeTextFld.getText();
        String manufacturer = manufacturedByTextFld.getText();
        String manufacturedyear = manufacturedYearTextFld.getText();
        String capacity = airplaneCapacityTextFld.getText();
        String certificate = certificateTextFld.getText();
        //Airplane A = fleet.addPlanes();
        A.setSerialNumber(serialnumber);
        A.setModelNumber(modelnumber);
        A.setDepartureTime(departuretime);
        A.setManufacturer(manufacturer);
        A.setManufacturedYear(manufacturedyear);
        A.setCapacity(capacity);
        A.setValidity(certificate); 
       
        
        JOptionPane.showMessageDialog(null, "Fleet successfully Updated!");
        displaytable();
    }
    }//GEN-LAST:event_savejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airplaneCapacityTextFld;
    private javax.swing.JTextField certificateTextFld;
    private javax.swing.JTextField departureTimeTextFld;
    private javax.swing.JButton fleetViewButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField manufacturedByTextFld;
    private javax.swing.JTextField manufacturedYearTextFld;
    private javax.swing.JTextField modelNoTextFld;
    private javax.swing.JButton savejButton;
    private javax.swing.JTextField serialNoTextFld;
    private javax.swing.JButton updatejButton;
    private javax.swing.JTable viewFleetTable;
    // End of variables declaration//GEN-END:variables

    private boolean validData() {
        //To change body of generated methods, choose Tools | Templates.
        if(serialNoTextFld.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Serial Number..");
            return false;
        }
         if(modelNoTextFld.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Model Number..");
            return false;
        }
         if(departureTimeTextFld.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Departure Time..");
            return false;
        }
         if(manufacturedByTextFld.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Manufacturer name..");
            return false;
        }
         if(manufacturedYearTextFld.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Manufactured Year..");
            return false;
        }
         if(airplaneCapacityTextFld.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Seating Capacity of Airplane..");
            return false;
        }
         if(certificateTextFld.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter the Certificate Valid till Year..");
            return false;
        }
        
         return true;
         
    }
    }

    

    

   

