/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import Business.Supplier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author cheta
 */
public class CreateProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateProductJPanel
     */
    private JPanel userProcessContainer;
    private Supplier supplier;
    public CreateProductJPanel(JPanel userProcessContainer,Supplier supplier) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplier = supplier;
        marketrevenuecombo();
    }

    
    public void marketrevenuecombo()
    {
        marketjComboBox2.removeAllItems();
        Object row1 = new Object();
        row1= "student";
        marketjComboBox2.addItem(row1);
        
        Object row2 = new Object();
        row2= "business";
        marketjComboBox2.addItem(row2);
        
        Object row3 = new Object();
        row3= "finance";
        marketjComboBox2.addItem(row3);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        productNamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ceilingjTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        floorJTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        qtyTextField3 = new javax.swing.JTextField();
        addProductJButton1 = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        marketCeilingTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        marketFloorTextField6 = new javax.swing.JTextField();
        marketjComboBox2 = new javax.swing.JComboBox();

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD PRODUCT");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product Name :");

        productNamejTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        productNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNamejTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Celing Price :");

        ceilingjTextField1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ceilingjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceilingjTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Floor Price :");

        floorJTextField2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        floorJTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorJTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quantity :");

        qtyTextField3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        qtyTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTextField3ActionPerformed(evt);
            }
        });

        addProductJButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addProductJButton1.setText("Add Product");
        addProductJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductJButton1ActionPerformed(evt);
            }
        });

        backjButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backjButton.setText("<< Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Market :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Market Ceiling :");

        marketCeilingTextField5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        marketCeilingTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketCeilingTextField5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Market Floor :");

        marketFloorTextField6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        marketFloorTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketFloorTextField6ActionPerformed(evt);
            }
        });

        marketjComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(productNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ceilingjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(floorJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qtyTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(addProductJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backjButton))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(marketjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(marketFloorTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(marketCeilingTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(productNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ceilingjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(floorJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(qtyTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marketjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(marketCeilingTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(marketFloorTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(addProductJButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(backjButton)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNamejTextFieldActionPerformed

    private void ceilingjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceilingjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceilingjTextField1ActionPerformed

    private void floorJTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorJTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorJTextField2ActionPerformed

    private void qtyTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTextField3ActionPerformed

    private void addProductJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductJButton1ActionPerformed
        // TODO add your handling code here:
        if (validData())
        {
            Product p = supplier.getProductCatalog().addProduct();
            p.setProductName(productNamejTextField.getText());
            p.setCeilingPrice(Integer.parseInt(ceilingjTextField1.getText()));
            p.setFloorPrice(Integer.parseInt(floorJTextField2.getText()));
            p.setQuantity(Integer.parseInt(qtyTextField3.getText()));
            p.getMarketOffer().setCeilingPrice(Integer.parseInt(marketCeilingTextField5.getText()));
            p.getMarketOffer().setFloorPrice(Integer.parseInt(marketFloorTextField6.getText()));
            p.getMarketOffer().getMarket().setMarketName((String) marketjComboBox2.getSelectedItem());

            JOptionPane.showMessageDialog(null, "Product added!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        

    }//GEN-LAST:event_addProductJButton1ActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length-1];
        SupplierJPanel supplierjpanel = (SupplierJPanel)component;
        supplierjpanel.populatetable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void marketCeilingTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketCeilingTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marketCeilingTextField5ActionPerformed

    private void marketFloorTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketFloorTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marketFloorTextField6ActionPerformed
    private boolean validData() 
    {
        if(productNamejTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Product Name..");
            return false;
        }
        if(ceilingjTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter ceiling Price..");
            return false;
        }
        if(floorJTextField2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Floor Price..");
            return false;
        }
        if(qtyTextField3.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Quantity..");
            return false;
        }
        if(marketCeilingTextField5.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Market Ceiling price..");
            return false;
        }
        if(marketFloorTextField6.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Market floor price..");
            return false;
        }
        return true;
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductJButton1;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField ceilingjTextField1;
    private javax.swing.JTextField floorJTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField marketCeilingTextField5;
    private javax.swing.JTextField marketFloorTextField6;
    private javax.swing.JComboBox marketjComboBox2;
    private javax.swing.JTextField productNamejTextField;
    private javax.swing.JTextField qtyTextField3;
    // End of variables declaration//GEN-END:variables
}
