/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Business;
import Business.Customer;
import Business.Supplier;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cheta
 */
public class manageSuppliersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form manageSuppliersJPanel
     */
    private Business business;
    private JPanel userProcessContainer;
   private ArrayList<Supplier> supplierList;
    
    public manageSuppliersJPanel(JPanel userProcessContainer,Business business, ArrayList<Supplier> supplierList) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.supplierList=supplierList;
        this.business=business;
        refreshTable();
    }
    public void refreshTable()
    {
        
        DefaultTableModel model = (DefaultTableModel) supplierjTable.getModel();
        model.setRowCount(0);
        for (Supplier s : supplierList) {
            Object row[] = new Object[1];
            row[0] = s;
            model.addRow(row);
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierjTable = new javax.swing.JTable();
        BackjButton = new javax.swing.JButton();
        viewSupplierjButton1 = new javax.swing.JButton();
        removeSupplierjButton2 = new javax.swing.JButton();
        addSupplierjButton3 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MANAGE SUPPLIERS");

        supplierjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(supplierjTable);

        BackjButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackjButton.setText("<< LogOut");
        BackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButtonActionPerformed(evt);
            }
        });

        viewSupplierjButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewSupplierjButton1.setText("View Suppier");
        viewSupplierjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupplierjButton1ActionPerformed(evt);
            }
        });

        removeSupplierjButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        removeSupplierjButton2.setText("Remove Supplier");
        removeSupplierjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSupplierjButton2ActionPerformed(evt);
            }
        });

        addSupplierjButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addSupplierjButton3.setText("Add Supplier");
        addSupplierjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierjButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(BackjButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewSupplierjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removeSupplierjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addSupplierjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewSupplierjButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeSupplierjButton2)
                    .addComponent(addSupplierjButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(BackjButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length-1];
        LoginJPanel loginjpanel = (LoginJPanel)component;
        loginjpanel.reset();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackjButtonActionPerformed

    private void viewSupplierjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupplierjButton1ActionPerformed
        // TODO add your handling code here:
        
        int row = supplierjTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
            Supplier s = (Supplier)supplierjTable.getValueAt(row,0);
            ViewSupplierJPanel panel = new ViewSupplierJPanel(userProcessContainer,s);
            userProcessContainer.add("ViewSupplierJPanel", panel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);            
        }
        
        
         
    }//GEN-LAST:event_viewSupplierjButton1ActionPerformed

    private void removeSupplierjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSupplierjButton2ActionPerformed
        // TODO add your handling code here:
        int row = supplierjTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Supplier s = (Supplier) supplierjTable.getValueAt(row, 0);
        business.getSupplierDirectory().removeSupplier(s);
        JOptionPane.showMessageDialog(null, "Supplier Data Removed");
        refreshTable();
        
    }//GEN-LAST:event_removeSupplierjButton2ActionPerformed

    private void addSupplierjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierjButton3ActionPerformed
        // TODO add your handling code here:
        
         AdminLoginJPanel panel = new AdminLoginJPanel(userProcessContainer,business,business.getSupplierDirectory().getSupplierList());
         userProcessContainer.add("AdminLoginJPanel", panel);
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
         layout.next(userProcessContainer);
    }//GEN-LAST:event_addSupplierjButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackjButton;
    private javax.swing.JButton addSupplierjButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeSupplierjButton2;
    private javax.swing.JTable supplierjTable;
    private javax.swing.JButton viewSupplierjButton1;
    // End of variables declaration//GEN-END:variables
}
