/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Business;
import Business.Customer;
import Business.Order;
import Business.OrderItem;
import Business.Person;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akhilesh Kashyap
 */
public class ReviewSalesOrderHistory extends javax.swing.JPanel {

    /**
     * Creates new form ReviewSalesOrderHistory
     */
    private JPanel userProcessContainer;
    private Business business;
    private Person person;
    private ArrayList<Order> customerOrderList;
    private ArrayList<Customer> customerOrder;
    public ReviewSalesOrderHistory(JPanel userProcessContainer, Person person, Business business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business = business;
        this.person = person;
        customerOrder = business.getCustomerDiretory().getCustomerList();
        populate();
    }
    
    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
        for(OrderItem oi : person.getOrders()) {
            Object row[] = new Object[7];
            row[0] = oi;
            row[1] = oi.getProduct().getCeilingPrice();
                row[2] = oi.getProduct().getFloorPrice();
            row[3] = oi.getPaidPrice()*oi.getQuantity();
            
            for(Customer c: customerOrder) {
                Order o = c.getOrder();
                for(OrderItem oitem: o.getOrderList()) 
                {
                    if(oitem.equals(oi)) {
                     row[6] = c.getCustomerName();
                    }
                    if(oi.getProduct().getMarketOffer().getMarket().getMarketName().equals(c.getMarket().getMarketName())) {
                row[4] = oi.getProduct().getMarketOffer().getCeilingPrice();
            row[5] = oi.getProduct().getMarketOffer().getFloorPrice();
            }
                }
            }
            
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        logoutjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Ceiling Price", "Floor Price", "Sold Price", "Offer Ceiling", "Offer Floor", "Customer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 88, 863, 233));

        logoutjButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logoutjButton.setText("<< Back");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });
        add(logoutjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 530, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CUSTOMERS SALES ORDER HISTORY");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 973, 43));
    }// </editor-fold>//GEN-END:initComponents

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutjButton;
    // End of variables declaration//GEN-END:variables
}
