/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Supplier;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Product.Product;
import Business.Product.ProductCatalog;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.AdministrativeRole.ViewRequestsJPanel;
import utility.Validator;

/**
 *
 * @author cheta
 */
public class SupplierLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierLoginJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private EcoSystem business;
    private ProductCatalog productlist;
    public SupplierLoginJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.business=business;
        
        populate();
    }
    
    private void populate() {
       productlist = enterprise.getProductList();
       DefaultTableModel model = (DefaultTableModel)productInventoryjTable1.getModel();
       model.setRowCount(0);
       
       for(Product product : productlist.getProductList()) {
           Object[] row = new Object[2];
           row[0] = product;
           row[1] = product.getPrice();
           model.addRow(row);
       }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productInventoryjTable1 = new javax.swing.JTable();
        addProductsjButton2 = new javax.swing.JButton();
        productNamejTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backjButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        priceTextField3 = new javax.swing.JTextField();
        deletejButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(84, 162, 168));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Supplier Login");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 900, 52));

        productInventoryjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productInventoryjTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 89, 322, 133));

        addProductsjButton2.setBackground(new java.awt.Color(255, 255, 255));
        addProductsjButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addProductsjButton2.setForeground(new java.awt.Color(84, 162, 168));
        addProductsjButton2.setText("Add");
        addProductsjButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addProductsjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductsjButton2ActionPerformed(evt);
            }
        });
        add(addProductsjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 429, 82, 30));

        productNamejTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productNamejTextField2KeyPressed(evt);
            }
        });
        add(productNamejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 340, 124, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(84, 162, 168));
        jLabel1.setText("Product Name : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 339, -1, 23));

        backjButton3.setBackground(new java.awt.Color(255, 255, 255));
        backjButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backjButton3.setForeground(new java.awt.Color(84, 162, 168));
        backjButton3.setText("<< Back");
        backjButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton3ActionPerformed(evt);
            }
        });
        add(backjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 503, 77, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(84, 162, 168));
        jLabel2.setText("Price :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 380, -1, 23));

        priceTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceTextField3KeyPressed(evt);
            }
        });
        add(priceTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 381, 124, -1));

        deletejButton1.setBackground(new java.awt.Color(255, 255, 255));
        deletejButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deletejButton1.setForeground(new java.awt.Color(84, 162, 168));
        deletejButton1.setText("Delete");
        deletejButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(deletejButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 240, 75, 33));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void addProductsjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductsjButton2ActionPerformed
        // TODO add your handling code here:
        Product prod = productlist.addProduct();
        prod.setProductName(productNamejTextField2.getText());
        prod.setPrice(Integer.parseInt(priceTextField3.getText()));
        populate();
    }//GEN-LAST:event_addProductsjButton2ActionPerformed

    private void productNamejTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNamejTextField2KeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, productNamejTextField2);
    }//GEN-LAST:event_productNamejTextField2KeyPressed

    private void priceTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTextField3KeyPressed
        // TODO add your handling code here:
        Validator.onlyInteger(evt, priceTextField3);
    }//GEN-LAST:event_priceTextField3KeyPressed

    private void backjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductsjButton2;
    private javax.swing.JButton backjButton3;
    private javax.swing.JButton deletejButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField priceTextField3;
    private javax.swing.JTable productInventoryjTable1;
    private javax.swing.JTextField productNamejTextField2;
    // End of variables declaration//GEN-END:variables
}
