/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterPriseType.Hospital;
import Business.Network.Network;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utility.Validator;

/**
 *
 * @author cheta
 */
public class RevenueNewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RevenueNewJPanel
     */
    
    private EcoSystem system;
    private JPanel userProcessContainer;
    public RevenueNewJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system=system;
        
        
        
        populateNetworkComboBox();
        populateRevenue();
    }
    
    public void populateRevenue() {
        
    }
    
    private void populateNetworkComboBox(){
        networkjComboBox1.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            networkjComboBox1.addItem(network);
        }
    }
     private ArrayList<Network> networklist;
    private ArrayList<Enterprise> enterpriseDir;
    
    private void populateEnterpriseComboBox(){
        hospitaljComboBox.removeAllItems();
        
        networklist  = system.getNetworkList();
        Network network = networklist.get(0);
        
        enterpriseDir = network.getEnterpriseDirectory().getEnterpriseList();
        for(Enterprise enterprise : enterpriseDir)
        {
            Enterprise.EnterPriseType type = Hospital;
            if(enterprise.getEnterpriseType().equals(type)) 
            {
                 hospitaljComboBox.addItem(enterprise);
            }
        
        }
        
    }

   
    
//    private void populatehospital() 
//    {
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        networkjComboBox1 = new javax.swing.JComboBox();
        hospitaljComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalBudgetjTextField1 = new javax.swing.JTextField();
        revenueEarnedjTextField2 = new javax.swing.JTextField();
        currentSpendingjTextField3 = new javax.swing.JTextField();
        addBudgetjButton1 = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(84, 162, 168));
        setToolTipText("");
        setEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(84, 162, 168));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REVENUE OF ENTERPRISE");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 40, 900, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(84, 162, 168));
        jLabel2.setText("Network :");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(84, 162, 168));
        jLabel4.setText("Hospital :");
        jLabel4.setToolTipText("");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        networkjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkjComboBox1ActionPerformed(evt);
            }
        });
        add(networkjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 114, -1));

        hospitaljComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitaljComboBoxActionPerformed(evt);
            }
        });
        add(hospitaljComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 112, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(84, 162, 168));
        jLabel5.setText("Total Budget :");
        jLabel5.setToolTipText("");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(84, 162, 168));
        jLabel6.setText("Current Spending :");
        jLabel6.setToolTipText("");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(84, 162, 168));
        jLabel7.setText("Revenue Earned :");
        jLabel7.setToolTipText("");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        totalBudgetjTextField1.setEnabled(false);
        totalBudgetjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBudgetjTextField1ActionPerformed(evt);
            }
        });
        totalBudgetjTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalBudgetjTextField1KeyPressed(evt);
            }
        });
        add(totalBudgetjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 112, -1));

        revenueEarnedjTextField2.setEnabled(false);
        add(revenueEarnedjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 112, -1));

        currentSpendingjTextField3.setEnabled(false);
        currentSpendingjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentSpendingjTextField3ActionPerformed(evt);
            }
        });
        add(currentSpendingjTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 112, -1));

        addBudgetjButton1.setBackground(new java.awt.Color(255, 255, 255));
        addBudgetjButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addBudgetjButton1.setForeground(new java.awt.Color(84, 162, 168));
        addBudgetjButton1.setText("Increase Budget");
        addBudgetjButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBudgetjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBudgetjButton1ActionPerformed(evt);
            }
        });
        add(addBudgetjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 120, 34));

        backjButton.setBackground(new java.awt.Color(255, 255, 255));
        backjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backjButton.setForeground(new java.awt.Color(84, 162, 168));
        backjButton.setText("<< Back");
        backjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 492, 93, 42));

        saveJButton.setBackground(new java.awt.Color(255, 255, 255));
        saveJButton.setForeground(new java.awt.Color(84, 162, 168));
        saveJButton.setText("Save");
        saveJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveJButton.setEnabled(false);
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 273, 70, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void networkjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkjComboBox1ActionPerformed
        // TODO add your handling code here:
        Network network = (Network) networkjComboBox1.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox();
        }
    }//GEN-LAST:event_networkjComboBox1ActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backjButtonActionPerformed

    private void currentSpendingjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentSpendingjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentSpendingjTextField3ActionPerformed

    private void totalBudgetjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBudgetjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBudgetjTextField1ActionPerformed

    private void totalBudgetjTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalBudgetjTextField1KeyPressed
        // TODO add your handling code here:
        Validator.onlyInteger(evt, totalBudgetjTextField1);
    }//GEN-LAST:event_totalBudgetjTextField1KeyPressed

    private void hospitaljComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitaljComboBoxActionPerformed
        // TODO add your handling code here:
        
        Enterprise enterprise = (Enterprise) hospitaljComboBox.getSelectedItem();
        
        int budget = enterprise.getBudget();
        int spending = enterprise.getRemaining();
        int revenue = enterprise.getRevenue();
        
        totalBudgetjTextField1.setText(String.valueOf(budget));
        currentSpendingjTextField3.setText(String.valueOf(spending));
        revenueEarnedjTextField2.setText(String.valueOf(revenue));
        
    }//GEN-LAST:event_hospitaljComboBoxActionPerformed

    private void addBudgetjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBudgetjButton1ActionPerformed
        // TODO add your handling code here:
        totalBudgetjTextField1.setEnabled(true);
        addBudgetjButton1.setEnabled(false);
        saveJButton.setEnabled(true);
        
    }//GEN-LAST:event_addBudgetjButton1ActionPerformed

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        
        Enterprise enterprise = (Enterprise) hospitaljComboBox.getSelectedItem();
        
        int newRevenue = Integer.parseInt(totalBudgetjTextField1.getText());
        
        if(newRevenue < 1 || newRevenue < enterprise.getBudget()) {
            JOptionPane.showMessageDialog(null, "Budget cant be 0 OR less than current budget");
        }
        else
        {
            enterprise.setBudget(newRevenue);
            JOptionPane.showMessageDialog(null, "Budget updated!");
            saveJButton.setEnabled(false);
            addBudgetjButton1.setEnabled(true);
            totalBudgetjTextField1.setEnabled(false);
        }
        
    }//GEN-LAST:event_saveJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBudgetjButton1;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField currentSpendingjTextField3;
    private javax.swing.JComboBox hospitaljComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox networkjComboBox1;
    private javax.swing.JTextField revenueEarnedjTextField2;
    private javax.swing.JButton saveJButton;
    private javax.swing.JTextField totalBudgetjTextField1;
    // End of variables declaration//GEN-END:variables
}
