/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkAreas;



import Business.CDC.Disease;
import Business.EcoSystem;
import Business.Supplier.Vaccine;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import utility.Validator;

/**
 *
 * @author cheta
 */
public class ManageVaccineDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePersonDirectoryJPanel
     */
   private JPanel userProcessContainer;
   private EcoSystem business;
 
    public ManageVaccineDirectoryJPanel(JPanel userProcessContainer, EcoSystem business){
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
       
        populateVaccineTable();
        populatecombo();
    }
    public void populateVaccineTable(){
         DefaultTableModel dtm= (DefaultTableModel) tblVaccine.getModel();
       dtm.setRowCount(0);
       for (Vaccine vaccine : business.getVaccineList().getVaccineList()) {
        
           Object[] row = new Object[2];
           row[0]= vaccine;
           row[1]=vaccine.getVaccineId();
           dtm.addRow(row);
       }  
       }
    
    public void populatecombo(){
        for (Disease disease : business.getDiseaseList().getDiseaseList()) {
            comboDisease.addItem(disease);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccine = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblwelcome = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtVaccineName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboDisease = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Name", "Vaccine ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVaccine);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 120, 590, 170));

        btnNew.setText("Create New Vaccine");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 150, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblwelcome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(lblwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 240, 20));

        btnDelete.setText("Delete Vaccine");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 180, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Create Vaccine ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 170, 30));

        txtVaccineName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVaccineNameKeyPressed(evt);
            }
        });
        add(txtVaccineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 120, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Manage Vaccine Directory");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 320, 30));

        add(comboDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 120, -1));

        jLabel1.setText("Disease: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        if(!txtVaccineName.getText().equals("")){
        Vaccine v= business.getVaccineList().addVaccine();
        v.setVaccineName(txtVaccineName.getText());
        v.setDisease((Disease) comboDisease.getSelectedItem());
        populateVaccineTable();
        }else{
             JOptionPane.showMessageDialog(null, "Enter value", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
          int selectedRow= tblVaccine.getSelectedRow();
         if(selectedRow<0){
             JOptionPane.showMessageDialog(null, "Please select the row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
      }
        else{
             
         Vaccine p=(Vaccine) tblVaccine.getValueAt(selectedRow, 0);

         business.getVaccineList().removeVaccine(p);
         
          JOptionPane.showMessageDialog(null, "You have successfully deleted the account");
        populateVaccineTable();
         }
         
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtVaccineNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVaccineNameKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtVaccineName);
    }//GEN-LAST:event_txtVaccineNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JComboBox comboDisease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JTable tblVaccine;
    private javax.swing.JTextField txtVaccineName;
    // End of variables declaration//GEN-END:variables
}
